name: Playwright Multi-Browser Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, edge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ "${{ matrix.browser }}" = "edge" ]; then
            python -m playwright install msedge
          else
            python -m playwright install ${{ matrix.browser }}
          fi

      - name: Run tests and generate HTML + trace
        run: |
          BROWSER=${{ matrix.browser }} PYTHONPATH=. pytest tests/ --html=report-${{ matrix.browser }}.html --self-contained-html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report-${{ matrix.browser }}
          path: report-${{ matrix.browser }}.html

      - name: Upload Playwright trace
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trace-${{ matrix.browser }}
          path: trace-${{ matrix.browser }}.zip
